import type { AgreementSchema, SignerRole } from "@/lib/vision/types";
import type { WorkflowStep, WorkflowRole } from "./types";

/**
 * Generate a sensible default workflow from an AgreementSchema. Each
 * non-pre-signed `signerRole` contributes one step; pre-signed blocks are
 * ignored because they're already done at ingest time.
 *
 * Ordering rules:
 *  1. "self" → first step (the person filling the form is the active party)
 *  2. "co-signer" → second step (same side, after self)
 *  3. "counterparty" → last step (opposing party signs after self + co-signer)
 *  4. approver/reviewer/witness — not generated by default (no vision source
 *     yet); reserved for future or manual editing.
 *
 * All flat fields and fieldGroup fields are assigned to the FIRST step that
 * has `self` role (the filler fills everything non-signature). If no "self"
 * block exists, they attach to the first step emitted.
 */
export function deriveDefaultWorkflow(schema: AgreementSchema): WorkflowStep[] {
  const rolePriority: Record<SignerRole, number> = {
    self: 0,
    "co-signer": 1,
    counterparty: 2,
    "pre-signed": 99,
  };

  const blocksByRole: Record<SignerRole, typeof schema.signatureBlocks> = {
    self: [],
    "co-signer": [],
    counterparty: [],
    "pre-signed": [],
  };
  for (const block of schema.signatureBlocks) {
    const role = (block.signerRole ?? "self") as SignerRole;
    blocksByRole[role].push(block);
  }

  const orderedRoles: SignerRole[] = (["self", "co-signer", "counterparty"] as const).filter(
    (r) => blocksByRole[r].length > 0,
  );

  // If nothing has a non-pre-signed block, fall back to a single self step so
  // every agreement has at least one workflow step.
  if (orderedRoles.length === 0) {
    return [
      {
        id: "step-self",
        label: "Fill and sign",
        role: "self",
        requiredFieldIds: collectAllFieldIds(schema),
        requiredSignatureBlockIds: [],
        order: 0,
      },
    ];
  }

  const allFieldIds = collectAllFieldIds(schema);
  const steps: WorkflowStep[] = orderedRoles.map((role, i) => {
    const blockIds = blocksByRole[role].map((b) => b.id);
    return {
      id: `step-${role}`,
      label: stepLabel(role),
      role: role as WorkflowRole,
      // All form fields belong to whichever step is "self" (or the first step).
      requiredFieldIds: i === 0 ? allFieldIds : [],
      requiredSignatureBlockIds: blockIds,
      order: i,
    };
  });

  // Sort by role priority just in case the array order already encodes it,
  // then re-assign `order` to match final index.
  steps.sort((a, b) => {
    const ar = rolePriority[(a.role as SignerRole) ?? "self"] ?? 99;
    const br = rolePriority[(b.role as SignerRole) ?? "self"] ?? 99;
    return ar - br;
  });
  steps.forEach((s, i) => {
    s.order = i;
  });

  return steps;
}

function stepLabel(role: SignerRole): string {
  switch (role) {
    case "self":
      return "You fill and sign";
    case "co-signer":
      return "Co-signer signs";
    case "counterparty":
      return "Counterparty reviews and signs";
    case "pre-signed":
      return "Already signed";
  }
}

function collectAllFieldIds(schema: AgreementSchema): string[] {
  const ids: string[] = [];
  for (const f of schema.fields) ids.push(f.id);
  for (const g of schema.fieldGroups) {
    for (let i = 0; i < g.initialInstances; i++) {
      for (const f of g.template) {
        ids.push(`${g.id}__${i}__${f.id}`);
      }
    }
  }
  return ids;
}
